### ISSUE TITLE
Online players doesn't get removed from game view

### ISSUE THREAD

**Issue by zars15** [CrescentCode/ValkyrieServer#6]
Online players get added properly, but they remain as online, even if they have left the game long time ago.

Also, the player names aren't retrieved properly, they appear as nil.

**Comment by Gskartwii** [comment]
Thanks for the report. I am aware of these bugs, and should get at least the latter on fixed shortly.

**Comment by Gskartwii** [comment]
I have finally verified that the above commit has fixed the player name issue. I couldn't before due to the server being down because of external reasons.

For the other issue, I have manually cleared the online players. The issue should be fixed server-side on the keepalive-tracking branch, but is waiting for Roblox-side changes to be done to the private player tracking module (which is private to prevent developers from spoofing play times)

**Comment by Gskartwii** [comment]
https://github.com/CrescentCode/ValkyrieServer/commit/ee2739d6a93dd3a8b96d48027b37d35bd7b14e86 should have fixed the issue server-side, but the Roblox-side tracking module still needs to be changed.

**Comment by Gskartwii** [comment]
Forgot to close this, it's already fixed though.
